"""task type 

Revision ID: 26662f7fd2a5
Revises: b05f7c216537
Create Date: 2021-12-11 00:11:37.819457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26662f7fd2a5'
down_revision = 'b05f7c216537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_type', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task_type')
    # ### end Alembic commands ###
