"""empty message

Revision ID: 3a94fcff3f6e
Revises: c1b218206af5
Create Date: 2021-12-13 02:54:25.418614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a94fcff3f6e'
down_revision = 'c1b218206af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('general', 'emoji')
    op.drop_column('online_meetings', 'host')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('online_meetings', sa.Column('host', sa.VARCHAR(length=50), nullable=True))
    op.add_column('general', sa.Column('emoji', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
