"""empty message

Revision ID: 6ed0d3efc180
Revises: 26662f7fd2a5
Create Date: 2021-12-11 19:27:51.631559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ed0d3efc180'
down_revision = '26662f7fd2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('desc', mysql.VARCHAR(length=350), nullable=True))
    # ### end Alembic commands ###
