"""empty message

Revision ID: c65b7ce32664
Revises: faf7804c9d3c
Create Date: 2021-12-13 01:10:19.206313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65b7ce32664'
down_revision = 'faf7804c9d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('travel', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel', 'end_date')
    op.drop_column('travel', 'start_date')
    # ### end Alembic commands ###
