"""empty message

Revision ID: faf7804c9d3c
Revises: d3067ab836d2
Create Date: 2021-12-13 01:09:32.524286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf7804c9d3c'
down_revision = 'd3067ab836d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deadlines', 'date')
    # ### end Alembic commands ###
